// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Footer': typeof import("../components/Footer.vue")['default'],
    'LazyText': typeof import("../components/LazyText.vue")['default'],
    'Nav': typeof import("../components/Nav.vue")['default'],
    'RestaurantRow': typeof import("../components/restaurant/Row.vue")['default'],
    'RestaurantTable': typeof import("../components/restaurant/Table.vue")['default'],
    'TestMyButton': typeof import("../components/test/MyButton.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default'],
    'LazyLazyText': typeof import("../components/LazyText.vue")['default'],
    'LazyNav': typeof import("../components/Nav.vue")['default'],
    'LazyRestaurantRow': typeof import("../components/restaurant/Row.vue")['default'],
    'LazyRestaurantTable': typeof import("../components/restaurant/Table.vue")['default'],
    'LazyTestMyButton': typeof import("../components/test/MyButton.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Footer: typeof import("../components/Footer.vue")['default']
export const LazyText: typeof import("../components/LazyText.vue")['default']
export const Nav: typeof import("../components/Nav.vue")['default']
export const RestaurantRow: typeof import("../components/restaurant/Row.vue")['default']
export const RestaurantTable: typeof import("../components/restaurant/Table.vue")['default']
export const TestMyButton: typeof import("../components/test/MyButton.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyLazyText: typeof import("../components/LazyText.vue")['default']
export const LazyNav: typeof import("../components/Nav.vue")['default']
export const LazyRestaurantRow: typeof import("../components/restaurant/Row.vue")['default']
export const LazyRestaurantTable: typeof import("../components/restaurant/Table.vue")['default']
export const LazyTestMyButton: typeof import("../components/test/MyButton.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
